INSERT INTO "Skill" ("id", "name", "category")
VALUES
  ('skill_typescript_language', 'TypeScript', 'LANGUAGE'),
  ('skill_javascript_language', 'JavaScript', 'LANGUAGE'),
  ('skill_python_language', 'Python', 'LANGUAGE'),
  ('skill_go_language', 'Go', 'LANGUAGE'),
  ('skill_java_language', 'Java', 'LANGUAGE'),
  ('skill_kotlin_language', 'Kotlin', 'LANGUAGE'),
  ('skill_swift_language', 'Swift', 'LANGUAGE'),
  ('skill_ruby_language', 'Ruby', 'LANGUAGE'),
  ('skill_php_language', 'PHP', 'LANGUAGE'),
  ('skill_csharp_language', 'C#', 'LANGUAGE'),
  ('skill_cpp_language', 'C++', 'LANGUAGE'),
  ('skill_rust_language', 'Rust', 'LANGUAGE'),
  ('skill_react_framework', 'React', 'FRAMEWORK'),
  ('skill_nextjs_framework', 'Next.js', 'FRAMEWORK'),
  ('skill_vuejs_framework', 'Vue.js', 'FRAMEWORK'),
  ('skill_nuxt_framework', 'Nuxt', 'FRAMEWORK'),
  ('skill_angular_framework', 'Angular', 'FRAMEWORK'),
  ('skill_svelte_framework', 'Svelte', 'FRAMEWORK'),
  ('skill_nodejs_framework', 'Node.js', 'FRAMEWORK'),
  ('skill_nestjs_framework', 'NestJS', 'FRAMEWORK'),
  ('skill_django_framework', 'Django', 'FRAMEWORK'),
  ('skill_fastapi_framework', 'FastAPI', 'FRAMEWORK'),
  ('skill_ruby_on_rails_framework', 'Ruby on Rails', 'FRAMEWORK'),
  ('skill_laravel_framework', 'Laravel', 'FRAMEWORK'),
  ('skill_aspnet_core_framework', 'ASP.NET Core', 'FRAMEWORK'),
  ('skill_dotnet_framework', '.NET Framework', 'FRAMEWORK'),
  ('skill_spring_boot_framework', 'Spring Boot', 'FRAMEWORK'),
  ('skill_flutter_framework', 'Flutter', 'FRAMEWORK'),
  ('skill_react_native_framework', 'React Native', 'FRAMEWORK'),
  ('skill_aws_infra', 'AWS', 'INFRA'),
  ('skill_google_cloud_infra', 'Google Cloud', 'INFRA'),
  ('skill_azure_infra', 'Azure', 'INFRA'),
  ('skill_docker_infra', 'Docker', 'INFRA'),
  ('skill_kubernetes_infra', 'Kubernetes', 'INFRA'),
  ('skill_terraform_infra', 'Terraform', 'INFRA'),
  ('skill_postgresql_database', 'PostgreSQL', 'DATABASE'),
  ('skill_mysql_database', 'MySQL', 'DATABASE'),
  ('skill_mongodb_database', 'MongoDB', 'DATABASE'),
  ('skill_redis_database', 'Redis', 'DATABASE'),
  ('skill_bigquery_database', 'BigQuery', 'DATABASE'),
  ('skill_graphql_tool', 'GraphQL', 'TOOL'),
  ('skill_figma_tool', 'Figma', 'TOOL'),
  ('skill_unity_tool', 'Unity', 'TOOL'),
  ('skill_machine_learning_other', '機械学習', 'OTHER'),
  ('skill_llm_generative_ai_other', 'LLM・生成AI', 'OTHER'),
  ('skill_data_analysis_other', 'データ分析', 'OTHER'),
  ('skill_claude_code_other', 'Claude Code', 'OTHER'),
  ('skill_devin_other', 'Devin', 'OTHER'),
  ('skill_cursor_other', 'Cursor', 'OTHER'),
  ('skill_github_copilot_other', 'GitHub Copilot', 'OTHER'),
  ('skill_codex_other', 'Codex', 'OTHER')
ON CONFLICT ("name") DO UPDATE
SET "category" = EXCLUDED."category";
